### ISSUE TITLE
Role management policy update doesn't fail with invalid Approval_EndUser_Assignment config

### ISSUE THREAD

**Issue by frasdav** [gofrontier-com/sheriff#11]
```
rules:
  - id: Approval_EndUser_Assignment
    patch:
      setting:
        approvalStages:
          - approvalStageTimeOutInDays: 1
            escalationTimeInMinutes: 0
            isApproverJustificationRequired: true
            isEscalationEnabled: false
            primaryApprovers:
              - userType: Group
                isBackup: false
                id: 756a8dd8-43c8-46a2-92a4-24a686a31b8d <--- If this is wrong, it doesn't fail.
                description: CSG-RBAC-Test
        isApprovalRequired: true
```
